# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af78dbaea7f4b439051797f0e0240469071c79cf30f8c7492dfc99557504c5e5e0139d3185b8419eb294b3bd8d16850f362eaab310ff5450ec40259cb3063143

test:
  secret_key_base: 535a0273ef9cac3d30fda013ecb37b2d949d84f54b65141aef86d2eb076683fa6e18deca3451c8769b7d297e24743448a454cf58f280b86f516c203ce31689de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
